// Code generated by "stringer -type HttpStatusCode -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[NoContent-204]
	_ = x[BadRequest-400]
	_ = x[NotFound-404]
	_ = x[InternalServerError-500]
}

const (
	_HttpStatusCode_name_0 = "SUCCESS"
	_HttpStatusCode_name_1 = "NO_CONTENT"
	_HttpStatusCode_name_2 = "BAD_REQUEST"
	_HttpStatusCode_name_3 = "NOT_FOUND"
	_HttpStatusCode_name_4 = "INTERNAL_SERVER_ERROR"
)

func (i HttpStatusCode) String() string {
	switch {
	case i == 200:
		return _HttpStatusCode_name_0
	case i == 204:
		return _HttpStatusCode_name_1
	case i == 400:
		return _HttpStatusCode_name_2
	case i == 404:
		return _HttpStatusCode_name_3
	case i == 500:
		return _HttpStatusCode_name_4
	default:
		return "HttpStatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
