// Code generated by "stringer --type Status --trimprefix status --linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statusSuccess-200]
	_ = x[statusNoContent-204]
	_ = x[statusBadRequest-400]
	_ = x[statusInternalServerError-500]
}

const (
	_Status_name_0 = "SUCCESS"
	_Status_name_1 = "NO_CONTENT"
	_Status_name_2 = "BAD_REQUEST"
	_Status_name_3 = "INTERNAL_SERVER_ERROR"
)

func (i Status) String() string {
	switch {
	case i == 200:
		return _Status_name_0
	case i == 204:
		return _Status_name_1
	case i == 400:
		return _Status_name_2
	case i == 500:
		return _Status_name_3
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
