// Code generated by "stringer -type=Color"; DO NOT EDIT.

package car

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[White-1]
	_ = x[Gray-2]
	_ = x[Red-3]
}

const _Color_name = "WhiteGrayRed"

var _Color_index = [...]uint8{0, 5, 9, 12}

func (i Color) String() string {
	i -= 1
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
